### ISSUE TITLE
How can I get `annotation_disease.json` file?

### ISSUE THREAD

**Issue by JihwanEom** [GaryGuTC/COMG_model#1]

**Comment by GaryGuTC** [comment]
Hi Jihwan,

So sorry for my carelessness, I have updated it [here](https://unisydneyedu-my.sharepoint.com/personal/tigu8498_uni_sydney_edu_au/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Ftigu8498%5Funi%5Fsydney%5Fedu%5Fau%2FDocuments%2FCOMG%5Fmodel%5Fweight&ga=1).
If you have other questions, please feel free to contact me.

Best regards,
Tiancheng
