### ISSUE TITLE
How can I generate annotation_disease.json file

### ISSUE THREAD

**Issue by reflelia** [GaryGuTC/COMG_model#3]
Is there any guides or code for generate annotation_disease.json?

And also in #1 , I cant download annotation_disease.json in unisydneyedu-my.sharepoint.com

Can you reupload this file in another site?

**Comment by GaryGuTC** [comment]
Hi 

I have double-checked that the link is available and it's open for everyone. Please check again [link](https://unisydneyedu-my.sharepoint.com/personal/tigu8498_uni_sydney_edu_au/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Ftigu8498%5Funi%5Fsydney%5Fedu%5Fau%2FDocuments%2FCOMG%5Fmodel%5Fweight&ga=1).

Best regards,
Tiancheng

**Comment by acefunbil** [comment]
my Github account doesn't have permission to access the link,how can i download annotation_disease.json

**Comment by GaryGuTC** [comment]
Hi 

I have updated it [here](https://github.com/GaryGuTC/COMG_model/tree/main?tab=readme-ov-file#json-files-and-checkpoints-download).
If you still can't access it. Please email me.

Best regards,
Tiancheng
