### ISSUE TITLE
How long does it take to segment a MIMIC-CXR dataset?

### ISSUE THREAD

**Issue by min121101** [GaryGuTC/COMG_model#5]
Hello,

thank you for the great work and the great repo.

![屏幕截图 2024-04-01 155258](https://github.com/GaryGuTC/COMG_model/assets/92525943/9b503ca3-1b20-4970-a660-5620323e4e1a)

It takes about 1 month to do MIMIC-CXR dataset segmentation on GPU, I don't know if this is normal？

**Comment by GaryGuTC** [comment]
Hi

Thank you for your interest in our work.

I consider this is not correct. The total time for segmentation is about 5h using Nvidia 3090 GPU, referer [here](https://github.com/GaryGuTC/COMG_model#generate-mask).
I guess you may not use GPU to segment, which will cause time to increase significantly. Please double-check that.

Best regard,
Tiancheng
