### ISSUE TITLE
这个RL的学习率是固定的嘛，从一开始训练就用RL吗？

### ISSUE THREAD

**Issue by ecust-sl** [GaryGuTC/COMG_model#8]
Is the learning rate of this RL fixed? Do you use RL from the beginning of training?

**Comment by GaryGuTC** [comment]
Hi 

1. I remember it's fixed, and I followed this [work](https://github.com/synlp/R2GenRL). 
2. I use RL in the RL stage training (The second stage).
 
Best regards,
Tiancheng
