### ISSUE TITLE
core dumped

### ISSUE THREAD

**Issue by ecust-sl** [GaryGuTC/COMG_model#9]
train_iu_xray.sh: line 21: 1749424 Segmentation fault      (core dumped) python main_train.py --image_dir /extra/shilei/dataset/physionet.org/files/iu_xray/images --ann_path /extra/shilei/dataset/physionet.org/files/iu_xray/annotation_disease.json --dataset_name iu_xray --max_seq_length 60 --threshold 3 --epochs 150 --batch_size 8 --lr_ve 1e-4 --lr_ed 5e-4 --step_size 10 --gamma 0.8 --num_layers 3 --topk 32 --cmm_size 2048 --cmm_dim 512 --seed 7580 --beam_size 3 --save_dir results/iu_xray/ --log_period 50 --early_stop 40
Why is this a problem?

**Comment by GaryGuTC** [comment]
Hi

I haven't seen this error before. Could you provide some extra details (like screenshots without any sensitive information)? 

Best regards,
Tiancheng

**Comment by ecust-sl** [comment]
> Hi
> 
> I haven't seen this error before. Could you provide some extra details (like screenshots without any sensitive information)?
> 
> Best regards, Tiancheng

<img width="1251" alt="image" src="https://github.com/GaryGuTC/COMG_model/assets/151110436/4830863a-cea5-4079-b15e-bedcf7b52af5">
这个是报错的图片，可以帮忙看一下问题貌似出现在resnet101那里

**Comment by ecust-sl** [comment]
> > Hi
> > I haven't seen this error before. Could you provide some extra details (like screenshots without any sensitive information)?
> > Best regards, Tiancheng
> 
> <img alt="image" width="1251" src="https://private-user-images.githubusercontent.com/151110436/323199898-4830863a-cea5-4079-b15e-bedcf7b52af5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNTM3ODMsIm5iZiI6MTcxMzM1MzQ4MywicGF0aCI6Ii8xNTExMTA0MzYvMzIzMTk5ODk4LTQ4MzA4NjNhLWNlYTUtNDA3OS1iMTVlLWJlZGNmN2I1MmFmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QxMTMxMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZjRkZDU1YzBiYjIyMWFlNjNlMDBmNjYyZGE2ZTgzYjkwYWI2MzNhMDRhOWQ0OWM5NTlkNDJkNGE1ZDg3YmUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6jldU-PRlHnY7GY0_ISgfP0Y2LmwNhzyRUX3512HxOI"> 这个是报错的图片，可以帮忙看一下问题貌似出现在resnet101那里

<img width="826" alt="image" src="https://github.com/GaryGuTC/COMG_model/assets/151110436/4bd0795e-b209-40dc-86d1-89b2befbf4b3">
在这里调用resnet101的时候报core dumped

**Comment by GaryGuTC** [comment]
I suggest that
1. Check the pytorch version. (I used torch 2.0.1 + cuda==11.8)
2. Please refer this [issue](https://github.com/pytorch/pytorch/issues/121222).

Hope this can help you
Best regards

**Comment by ecust-sl** [comment]
> I suggest that
> 
> 1. Check the pytorch version. (I used torch 2.0.1 + cuda==11.8)
> 2. Please refer this [issue](https://github.com/pytorch/pytorch/issues/121222).
> 
> Hope this can help you Best regards

Ok, thank you, I'm using torch=2.2.1 + cuda11.8 I'll try to modify the version of the torch
